"""Fix discovery relations

Revision ID: 02824191a412
Revises: 1bcdf83eaf55
Create Date: 2025-07-28 22:42:06.081018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02824191a412'
down_revision: Union[str, Sequence[str], None] = '1bcdf83eaf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment', sa.Column('identifier', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('environment_indentifier_key'), 'environment', type_='unique')
    op.create_unique_constraint(None, 'environment', ['identifier'])
    op.drop_column('environment', 'indentifier')
    op.add_column('organization', sa.Column('identifier', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('organization_indentifier_key'), 'organization', type_='unique')
    op.create_unique_constraint(None, 'organization', ['identifier'])
    op.drop_column('organization', 'indentifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('indentifier', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization', type_='unique')
    op.create_unique_constraint(op.f('organization_indentifier_key'), 'organization', ['indentifier'], postgresql_nulls_not_distinct=False)
    op.drop_column('organization', 'identifier')
    op.add_column('environment', sa.Column('indentifier', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'environment', type_='unique')
    op.create_unique_constraint(op.f('environment_indentifier_key'), 'environment', ['indentifier'], postgresql_nulls_not_distinct=False)
    op.drop_column('environment', 'identifier')
    # ### end Alembic commands ###
