"""Fix discovery relations

Revision ID: 1bcdf83eaf55
Revises: 5dc698d9b150
Create Date: 2025-07-28 22:23:25.785707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcdf83eaf55'
down_revision: Union[str, Sequence[str], None] = '5dc698d9b150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('identifier', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('enterprise_indentifier_key'), 'enterprise', type_='unique')
    op.create_unique_constraint(None, 'enterprise', ['identifier'])
    op.drop_column('enterprise', 'indentifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('indentifier', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enterprise', type_='unique')
    op.create_unique_constraint(op.f('enterprise_indentifier_key'), 'enterprise', ['indentifier'], postgresql_nulls_not_distinct=False)
    op.drop_column('enterprise', 'identifier')
    # ### end Alembic commands ###
